apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwd-validator
  labels:
    app: pwd-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwd-validator
  template:
    metadata:
      labels:
        app: pwd-validator
    spec:
      containers:
      - name: pwd-validator
        image: pwd-validator
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: REQUIREMENTS_PATH
          value: "/requirements.txt"
