apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - path: /validate
        backend:
          serviceName: pwd-validator
          servicePort: 8000