apiVersion: v1
kind: Service
metadata:
  name: pwd-validator
  labels:
    app: pwd-validator
spec:
  selector:
    app: pwd-validator
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    name: wordpress
    protocol: TCP
