name: Build
on: ["push"]

jobs:
  unittests:
    name: unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 2
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
      - name: tests
        working-directory: pwd_rules
        run: |
          python unitte.py

