name: Build
on: ["push"]

jobs:
  unittests:
    name: unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependencies
        working-directory: srcs
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies.txt
      - name: tests
        working-directory: srcs
        run: |
          python unitte.py
  docker:
    name: Kubernetes
    runs-on: ubuntu-latest
    needs: [unittests]
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t pwd-validator .
      - name: Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          config: k8s/cluster.yml
      - name: Deploy image
        run: |
          kubectl apply -f k8s/svc.yml
          kubectl apply -f k8s/deploy.yml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=90s
          kubectl apply -f k8s/nginx.yml
      - name: Test deployement
        run: |
          curl -s -X POST "http://localhost/validate" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"login\":\"toto\", \"password\":\"weak\"}"


