name: Build
on: ["push"]

jobs:
  unittests:
    name: unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependencies.txt
      - name: tests
        run: |
          python unitte.py

